version: '3.8'

services:
  todo-mysql:
    image: mysql:8
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tododb
    ports:
      - '3307:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-p123456']
      interval: 10s
      timeout: 5s
      retries: 5

  todo-backend:
    build: ./backend
    container_name: todo-backend
    environment:
      DB_HOST: todo-mysql
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: tododb
      DB_PORT: 3306
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    ports:
      - '3001:3001'
    depends_on:
      todo-mysql:
        condition: service_healthy

  todo-frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - '3000:3000'
    depends_on:
      - todo-backend

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '8025:8025'  # веб-интерфейс
      - '1025:1025'  # SMTP