name: CI/CD for ToDo List

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub (optional)
        if: false # убрать false если захочешь пушить в DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend Docker image
        run: docker build -t todo-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t todo-frontend ./frontend

      - name: Docker Compose UP
        run: docker compose up -d

      - name: Wait for MySQL to be healthy
        run: |
          echo "⏳ Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if docker exec todo-mysql mysqladmin ping -uroot -p123456 --silent; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "⏳ MySQL is not ready yet... retrying"
            sleep 2
          done

      - name: Check Backend Health
        run: |
          echo "🔄 Testing backend..."
          curl -f http://localhost:3001/api/tasks || (echo "❌ Backend failed" && exit 1)

      - name: Check Frontend Health
        run: |
          echo "🔄 Testing frontend..."
          curl -f http://localhost:3000 || (echo "❌ Frontend failed" && exit 1)

      - name: Docker Compose Down (Clean all)
        run: docker compose down --volumes --remove-orphans
