name: CI/CD for ToDo List (Frontend Only)

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build frontend Docker image
        run: docker build -t todo-frontend ./frontend

      - name: Start frontend container
        run: docker run -d -p 3000:3000 --name todo-frontend todo-frontend

      - name: Wait for frontend to be ready
        run: sleep 10

      - name: Test frontend
        run: curl -f http://localhost:3000 || exit 1

      - name: Stop frontend container
        run: docker stop todo-frontend && docker rm todo-frontend
