name: CI/CD for ToDo List

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest ./frontend

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest

      - name: Run Docker Compose for tests
        run: |
          docker compose up -d
          echo "Wait for containers to start..."
          sleep 15

      - name: Test Backend API
        run: curl -f http://localhost:3001/api/tasks || exit 1

      - name: Test Frontend
        run: curl -f http://localhost:3000 || exit 1

      - name: Stop containers
        run: docker compose down --volumes --remove-orphans

