name: CI/CD for ToDo List

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-test-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and Start Containers
        run: docker-compose up -d --build

      - name: Wait for MySQL to become ready (robust)
        run: |
          echo "Waiting for MySQL service to be healthy..."
          ATTEMPTS_LEFT=30
          until docker exec todo-mysql mysqladmin ping -h localhost -p123456 --silent; do
            if [ $ATTEMPTS_LEFT -eq 0 ]; then
              echo "MySQL did not become healthy in time!"
              docker-compose logs
              exit 1
            fi
            echo "MySQL is not ready yet... waiting (attempts left: $ATTEMPTS_LEFT)"
            ATTEMPTS_LEFT=$((ATTEMPTS_LEFT - 1))
            sleep 5
          done
          echo "✅ MySQL is ready!"

      - name: Test backend API
        run: curl -f http://localhost:3001/api/tasks || exit 1

      - name: Test frontend
        run: curl -f http://localhost:3000 || exit 1

      - name: Stop and remove containers
        run: docker-compose down --volumes --remove-orphans
